{{- $root := . -}}
{{- if .Values.jenkins.backup.enabled }}
{{- range .Values.jenkins.configurationAsCode.configurations }}
  {{ if .content }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .name }}
  namespace: {{ $root.Values.jenkins.namespace }}
{{- with .content }}
data: {{ toYaml . | nindent 2 }}
{{- end }}
  {{ end }}
{{ end }}
{{ end }}
