apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: cascs.jenkins.io
spec:
  group: jenkins.io
  names:
    kind: Casc
    listKind: CascList
    plural: cascs
    singular: casc
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: Casc is the Schema for the cascs API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: CascSpec defines the desired state of Casc
          properties:
            configurations:
              items:
                description: ConfigMapRef is reference to Kubernetes ConfigMap.
                type: string
              type: array
            secret:
              description: 'INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
                Important: Run "operator-sdk generate k8s" to regenerate code after
                modifying this file Add custom validation using kubebuilder tags:
                https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html'
              type: string
          required:
          - configurations
          - secret
          type: object
        status:
          description: CascStatus defines the observed state of Casc
          properties:
            lastTransitionTime:
              format: date-time
              type: string
            message:
              type: string
            phase:
              description: 'Phase is a simple, high-level summary of where the Casc
                is in its lifecycle. There are five possible phase values: Pending:
                The Casc has been accepted by the Kubernetes system, but one or more
                of the required resources have not been created. Available: All of
                the resources for the Casc are ready. Failed: At least one resource
                has experienced a failure. Unknown: For some reason the state of the
                Casc phase could not be obtained.'
              type: string
            reason:
              type: string
          required:
          - lastTransitionTime
          - phase
          type: object
      type: object
  version: v1alpha3
  versions:
  - name: v1alpha3
    served: true
    storage: true
