apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: jenkinsimagebuilds.jenkins.io
spec:
  group: jenkins.io
  names:
    kind: JenkinsImageBuild
    listKind: JenkinsImageBuildList
    plural: jenkinsimagebuilds
    singular: jenkinsimagebuild
  scope: Namespaced
  versions:
  - name: v1alpha2
    schema:
      openAPIV3Schema:
        description: JenkinsImageBuild is the Schema for the jenkinsimagebuilds API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: JenkinsImageBuildSpec defines the desired state of JenkinsImageBuild
            type: object
          status:
            description: JenkinsImageBuildStatus defines the observed state of JenkinsImageBuild
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
