apiVersion: jenkins.io/v1alpha2
kind: Jenkins
metadata:
  name: jenkins-sample
spec:
  configurationAsCode:
    configurations: []
    enabled: true
    defaultConfig: true
    enableAutoReload: true
  jenkinsAPISettings:
    authorizationStrategy: serviceAccount
  jenkinsImageRef: jenkinsimage-sample 
  master:
    basePlugins:
    - name: kubernetes
      version: "1.25.2"
    - name: workflow-job
      version: "2.40"
    - name: workflow-aggregator
      version: "2.6"
    - name: git
      version: "4.2.2"
    - name: job-dsl
      version: "1.77"
    - name: configuration-as-code
      version: "1.41"
    - name: configuration-as-code-groovy
      version: "1.1"
    - name: configuration-as-code-support
      version: "1.19"
    - name: kubernetes-credentials-provider
      version: "0.12.1"
    containers:
    - name: jenkins-master
      image: jenkins/jenkins:lts
      imagePullPolicy: Always
      livenessProbe:
        failureThreshold: 12
        httpGet:
          path: /login
          port: http
          scheme: HTTP
        initialDelaySeconds: 80
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 5
      readinessProbe:
        failureThreshold: 3
        httpGet:
          path: /login
          port: http
          scheme: HTTP
        initialDelaySeconds: 30
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 1
      resources:
        limits:
          cpu: 1500m
          memory: 3Gi
        requests:
          cpu: "1"
          memory: 500Mi



